name: Artists A

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write  # Required for committing changes
  pull-requests: write  # Required for creating or updating pull requests


jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Perform API requests and update data
      run: |
        python A.py
    - name: Create a new branch and commit changes
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update results'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     title: 'Update API results'
    #     body: 'Automated update of API results.'
    #     base: main
    #     head: update-data-branch
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
